$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1395042111823.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"ca048aebbfad4c3e844f0527ebb2b743",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a1949b1c402419e9a08e29cc8e4fcfe",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
          "id":"bffe9c9efc0e479bb4a6b5cd5c58cc41",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3E5B99},
            "location":{
              "x":258,
              "y":73},
            "size":{
              "width":285,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e128457a8a04f58b1f117252fcf2666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3E5B99},
                "location":{
                  "x":258,
                  "y":73},
                "size":{
                  "width":285,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u3.png"}},
{
          "id":"edf810744bfe44979a277cb1f657f522",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":56},
            "size":{
              "width":285,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60947aebccf45adbd731a552e46f56f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":56},
                "size":{
                  "width":285,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"3f46dffef039437baac436d57ce159bf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":304},
            "size":{
              "width":285,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d3bc342f10241e68bd98a3e73df2e8c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":384},
            "size":{
              "width":285,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"322de78a0a674a5a94298081accecd72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":258,
              "y":279},
            "size":{
              "width":92,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dcca54b048848ae8a68927ba6a80fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":279},
                "size":{
                  "width":92,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b689806df5fc41108789ddcfb79f3774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":258,
              "y":359},
            "size":{
              "width":92,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada3a48c8806420180634e68e8e8e6dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":359},
                "size":{
                  "width":92,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41f27470eeea4e3ab86a18a4dae82425",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":258,
              "y":449},
            "size":{
              "width":285,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56c1cb25fe9e4c50ad03e406b20c56ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":258,
                  "y":449},
                "size":{
                  "width":285,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Fields filled out<br> (If text on (Text Field) does not equal &quot;&quot; and text on (Text Field) does not equal &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["3f46dffef039437baac436d57ce159bf"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2d3bc342f10241e68bd98a3e73df2e8c"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"Case 1<br> (Else If text on (Text Field) equals &quot;&quot; and text on (Text Field) equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["3f46dffef039437baac436d57ce159bf"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2d3bc342f10241e68bd98a3e73df2e8c"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show userError",
                      "objectsToFades":[{
                          "objectPath":["81010f6116a249a3b81be03afb1f7097"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Show passwordError",
                      "objectsToFades":[{
                          "objectPath":["f765d03335774f65902ff7f33d415bac"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"Case 2<br> (Else If text on (Text Field) equals &quot;&quot; and text on (Text Field) does not equal &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["3f46dffef039437baac436d57ce159bf"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2d3bc342f10241e68bd98a3e73df2e8c"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show userError",
                      "objectsToFades":[{
                          "objectPath":["81010f6116a249a3b81be03afb1f7097"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Hide passwordError",
                      "objectsToFades":[{
                          "objectPath":["f765d03335774f65902ff7f33d415bac"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"Case 3<br> (Else If text on (Text Field) does not equal &quot;&quot; and text on (Text Field) equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["3f46dffef039437baac436d57ce159bf"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2d3bc342f10241e68bd98a3e73df2e8c"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show passwordError",
                      "objectsToFades":[{
                          "objectPath":["f765d03335774f65902ff7f33d415bac"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Hide userError",
                      "objectsToFades":[{
                          "objectPath":["81010f6116a249a3b81be03afb1f7097"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u13.png"}},
{
          "id":"f765d03335774f65902ff7f33d415bac",
          "label":"passwordError",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":350,
              "y":364},
            "size":{
              "width":193,
              "height":15},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dd0fd894f604b179bfec7561f25ec77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":364},
                "size":{
                  "width":193,
                  "height":15},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81010f6116a249a3b81be03afb1f7097",
          "label":"userError",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":350,
              "y":284},
            "size":{
              "width":193,
              "height":15},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa44cc9277d84bcca26a11a05ecf9ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":284},
                "size":{
                  "width":193,
                  "height":15},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}}},
  "objectPaths":{
    "0a1949b1c402419e9a08e29cc8e4fcfe":{
      "scriptId":"u0",
      "89ad40f4e4a845958f4f199ffc29cccd":{
        "scriptId":"u1"},
      "817028217dd1407aa5e9ad17a76d4c45":{
        "scriptId":"u2"}},
    "bffe9c9efc0e479bb4a6b5cd5c58cc41":{
      "scriptId":"u3"},
    "4e128457a8a04f58b1f117252fcf2666":{
      "scriptId":"u4"},
    "edf810744bfe44979a277cb1f657f522":{
      "scriptId":"u5"},
    "c60947aebccf45adbd731a552e46f56f":{
      "scriptId":"u6"},
    "3f46dffef039437baac436d57ce159bf":{
      "scriptId":"u7"},
    "2d3bc342f10241e68bd98a3e73df2e8c":{
      "scriptId":"u8"},
    "322de78a0a674a5a94298081accecd72":{
      "scriptId":"u9"},
    "1dcca54b048848ae8a68927ba6a80fcf":{
      "scriptId":"u10"},
    "b689806df5fc41108789ddcfb79f3774":{
      "scriptId":"u11"},
    "ada3a48c8806420180634e68e8e8e6dd":{
      "scriptId":"u12"},
    "41f27470eeea4e3ab86a18a4dae82425":{
      "scriptId":"u13"},
    "56c1cb25fe9e4c50ad03e406b20c56ca":{
      "scriptId":"u14"},
    "f765d03335774f65902ff7f33d415bac":{
      "scriptId":"u15"},
    "6dd0fd894f604b179bfec7561f25ec77":{
      "scriptId":"u16"},
    "81010f6116a249a3b81be03afb1f7097":{
      "scriptId":"u17"},
    "aa44cc9277d84bcca26a11a05ecf9ca9":{
      "scriptId":"u18"}}});