$axure.loadCurrentPage({
  "url":"event_list.html",
  "generationDate":new Date(1395042112283.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"ebe60a4b40c94ef7b7c0cc0e79675a1f",
    "type":"Axure:Page",
    "name":"Event List",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89c5420ddf1d4b4eabcb964348f552aa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"1a83fe49158f41059f9cd9ac5915885f"},
{
          "id":"9bbbc7df2f914ebb97fa25e86d485422",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14b6c0b6d6548baa4bd5f7d1e74fbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":50,
                  "y":100},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u48.png"}},
{
          "id":"516a13ddffe54a27b88890f389b2f6b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":154},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f99bfa83f5e480aa16cb72d44d2f73b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":154},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Painting Event Detail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"painting_event_detail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2f2bae13c804440a84d158d072cb894",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":194},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faa76557933448beb8eeb0b528544509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":194},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98aedd55de084a1db452bc6658be0c35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":240},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e39f39f979974171a831c0f7751e4030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":240},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c845d69664eb4da3978bdbf05a6ee774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":154},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c29241f9f3d641d89af4dde91acbd306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":154},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Painting Event Detail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"painting_event_detail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73fd4333bbff4c57b22a9de0adbee3e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":194},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac18b10fb544f429f62c5821f4707a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":194},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a883bdacc8541ef8ae0e070e94579df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":240},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cba1486678f435493abf6f1236579fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":240},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3efa429403a4cfe9dd4f6d3ec566baa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":50,
              "y":330},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf53e3928a144bc4b5c9610eb098f648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":50,
                  "y":330},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u48.png"}},
{
          "id":"fc3a9ea00b624c818cf2558bde102361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":384},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18fb35417b2e4349b0ec14ea71163397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":384},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a8c2ed96ea140e4b027d814a7dcc7e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":424},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27826213702147bd8ba5eefaf1365751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":424},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e71e3d574a1b4aa9a9e545c624dac852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":384},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aace474968c446aba0f9bb391d42f4c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":384},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8e626f11dbd414e89ccb3c2ee97666d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":424},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576a2c0b00f3405ca8742369275139ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":424},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e36d68e70e54fe98bfa847513fef9a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":530},
            "size":{
              "width":630,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9417bcfa8a414f1e8c7444d4e1f95cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":530},
                "size":{
                  "width":630,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a81bcf15460472ba5974c67e14b2ca0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"0273482aa7ee4170a3afc678347b88d3"},
{
          "id":"93108d742d784a44a86367d0423d8164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4965A0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":590,
              "y":162},
            "size":{
              "width":30,
              "height":14},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f88094eafd4184a913266fcaff3242",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4965A0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":590,
                  "y":162},
                "size":{
                  "width":30,
                  "height":14},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Painting Event Detail in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"painting_event_detail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/event_list/u77.png"}},
{
          "id":"021b8cea7b42417292375277cb5668bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4965A0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":590,
              "y":202},
            "size":{
              "width":30,
              "height":14},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e11b632105e544b082141de6edd94470",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4965A0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":590,
                  "y":202},
                "size":{
                  "width":30,
                  "height":14},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u77.png"}},
{
          "id":"c1eb05bc08f34e46ad8d73f0b6484f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4965A0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":590,
              "y":248},
            "size":{
              "width":30,
              "height":14},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"212b7da4512a48378d273c25c5792b68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4965A0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":590,
                  "y":248},
                "size":{
                  "width":30,
                  "height":14},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u77.png"}},
{
          "id":"90701e56b99746a8bbdfdabcb192bfa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4965A0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":590,
              "y":392},
            "size":{
              "width":30,
              "height":14},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e628a443f0d246d8a62f1334020b436e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4965A0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":590,
                  "y":392},
                "size":{
                  "width":30,
                  "height":14},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u77.png"}},
{
          "id":"f4eb1ed6ceb441969aa73133d8232d40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4965A0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":590,
              "y":432},
            "size":{
              "width":30,
              "height":14},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f0a25d3f99437e92c6bf961dbf0a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4965A0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":590,
                  "y":432},
                "size":{
                  "width":30,
                  "height":14},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u77.png"}}]}},
  "masters":{
    "1a83fe49158f41059f9cd9ac5915885f":{
      "packageId":"1a83fe49158f41059f9cd9ac5915885f",
      "type":"Axure:Master",
      "name":"Popup",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"13a7bd5da3e54308b6fca80087f9b4b1",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"937f1060be994331af4574941a5fe12f"},
{
            "id":"c30d817f6032488595406f350ca406e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":70},
              "size":{
                "width":760,
                "height":510},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"302f1fdd803c4ab98a96d23348f022f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":70},
                  "size":{
                    "width":760,
                    "height":510},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/event_list/u44.png"}},
{
            "id":"b0456e8008f243d3b6abbf2899dd0696",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":750,
                "y":70},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9605511848647c9bc4e38816b381f4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":750,
                    "y":70},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/event_list/u46.png"}}]}},
    "937f1060be994331af4574941a5fe12f":{
      "packageId":"937f1060be994331af4574941a5fe12f",
      "type":"Axure:Master",
      "name":"Home Screen",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c4cb6a00a86f43f4bcc0ef8c413442ab",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
            "id":"1e1186e7b2c94b6d9ad8ebbebfa093fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":345,
                "y":71},
              "size":{
                "width":110,
                "height":499},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9997acae723b49f99ca6b328071cc49a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":345,
                    "y":71},
                  "size":{
                    "width":110,
                    "height":499},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"0ac2936106af46658b63f3af3f1b688e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":170},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa30f9c5eb0a47f39ba133d861111634",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":170},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"b7b24062c1b248889e6c94f3b3c4e563",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":410},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f1fafef5cb4f40609d84800a8a759ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":410},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"5b6e84b065094b50954874095f65ca55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8e922ba8abe4dd888a162d96a5676a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"2f69187aaf56454d888631165e89433c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"838a13adcb2c4760879131c11a1d1308",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"89b47eb9cbd34f71afefec2bbbe6221a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"909526bc04c54e17913d83a5915d018c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"e7cc05c8b6d9497e9033bbc715aa05f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed00e4773ff64e6b81cf9daa624ba342",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"20309fb5c652419eaa1378a33aba38e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"64b7158854944bf292ca143f00d38f64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"452bb3de4d174450bc013c78e9312636",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a8f3d9d82354fc5be64b00c09bc99b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6463cb28a52941fbaf67e74bf36c093b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bbf091a8aae6434db2c20f9d16089409",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"65dc6ea3c2bc45e9bd903a8337420258",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47b8ab617fbf441b9dcdf907c3f15359",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"01d0201b24864181b86f93aa996a909c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"6fce1fcbd7b74a4fa90a699ee160c776"},
{
            "id":"a9e437461ac34e60a97d7ed400848015",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28637fe8e56f4d21a32304eb74b917cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"20f64c2556174e258c98ab86fa3416b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a2b391c7200447289083e1804d73fe9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"04f14d1465ba4288b4681cc7bfffc7f5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af5df1eb0271409da378d631ee6eea35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a2ff4b62f33049e78d12a1c7fe988137",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"195816fd62604e789555474ab2c2cc4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}},
    "6fce1fcbd7b74a4fa90a699ee160c776":{
      "packageId":"6fce1fcbd7b74a4fa90a699ee160c776",
      "type":"Axure:Master",
      "name":"Top Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1fc2d5a32fc04aee8625a29e1baeccac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f728946738cc43f8a3e29348456955bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"888b1d943b4e4702836e8be23c5c2192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cafb9e688c2244f59a4523ca4599f297",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"98153c8ab8b44e13b4b8e2e3f725fd83",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc399042f0b4b1f9aca768cc4b218cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"15e4f70427624088850f7ffe1b5bd001",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2efb20853bc34548abdd42d7e54c25b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}}]}},
    "0273482aa7ee4170a3afc678347b88d3":{
      "packageId":"0273482aa7ee4170a3afc678347b88d3",
      "type":"Axure:Master",
      "name":"Events Button Active",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b0ad981943d64ab590a2912ed96c062f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58e4ffa8ef6b45f0b8a92544a70dd660",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u44.png"}}]}}},
  "objectPaths":{
    "89c5420ddf1d4b4eabcb964348f552aa":{
      "scriptId":"u0",
      "13a7bd5da3e54308b6fca80087f9b4b1":{
        "scriptId":"u1",
        "c4cb6a00a86f43f4bcc0ef8c413442ab":{
          "scriptId":"u2",
          "89ad40f4e4a845958f4f199ffc29cccd":{
            "scriptId":"u3"},
          "817028217dd1407aa5e9ad17a76d4c45":{
            "scriptId":"u4"}},
        "1e1186e7b2c94b6d9ad8ebbebfa093fd":{
          "scriptId":"u5"},
        "9997acae723b49f99ca6b328071cc49a":{
          "scriptId":"u6"},
        "0ac2936106af46658b63f3af3f1b688e":{
          "scriptId":"u7"},
        "aa30f9c5eb0a47f39ba133d861111634":{
          "scriptId":"u8"},
        "b7b24062c1b248889e6c94f3b3c4e563":{
          "scriptId":"u9"},
        "f1fafef5cb4f40609d84800a8a759ef4":{
          "scriptId":"u10"},
        "5b6e84b065094b50954874095f65ca55":{
          "scriptId":"u11"},
        "f8e922ba8abe4dd888a162d96a5676a1":{
          "scriptId":"u12"},
        "2f69187aaf56454d888631165e89433c":{
          "scriptId":"u13"},
        "838a13adcb2c4760879131c11a1d1308":{
          "scriptId":"u14"},
        "89b47eb9cbd34f71afefec2bbbe6221a":{
          "scriptId":"u15"},
        "909526bc04c54e17913d83a5915d018c":{
          "scriptId":"u16"},
        "e7cc05c8b6d9497e9033bbc715aa05f9":{
          "scriptId":"u17"},
        "ed00e4773ff64e6b81cf9daa624ba342":{
          "scriptId":"u18"},
        "20309fb5c652419eaa1378a33aba38e3":{
          "scriptId":"u19"},
        "64b7158854944bf292ca143f00d38f64":{
          "scriptId":"u20"},
        "452bb3de4d174450bc013c78e9312636":{
          "scriptId":"u21"},
        "1a8f3d9d82354fc5be64b00c09bc99b1":{
          "scriptId":"u22"},
        "6463cb28a52941fbaf67e74bf36c093b":{
          "scriptId":"u23"},
        "bbf091a8aae6434db2c20f9d16089409":{
          "scriptId":"u24"},
        "65dc6ea3c2bc45e9bd903a8337420258":{
          "scriptId":"u25"},
        "47b8ab617fbf441b9dcdf907c3f15359":{
          "scriptId":"u26"},
        "01d0201b24864181b86f93aa996a909c":{
          "scriptId":"u27",
          "1fc2d5a32fc04aee8625a29e1baeccac":{
            "scriptId":"u28"},
          "f728946738cc43f8a3e29348456955bc":{
            "scriptId":"u29"},
          "888b1d943b4e4702836e8be23c5c2192":{
            "scriptId":"u30"},
          "cafb9e688c2244f59a4523ca4599f297":{
            "scriptId":"u31"},
          "98153c8ab8b44e13b4b8e2e3f725fd83":{
            "scriptId":"u32"},
          "cfc399042f0b4b1f9aca768cc4b218cb":{
            "scriptId":"u33"},
          "15e4f70427624088850f7ffe1b5bd001":{
            "scriptId":"u34"},
          "2efb20853bc34548abdd42d7e54c25b3":{
            "scriptId":"u35"}},
        "a9e437461ac34e60a97d7ed400848015":{
          "scriptId":"u36"},
        "28637fe8e56f4d21a32304eb74b917cb":{
          "scriptId":"u37"},
        "20f64c2556174e258c98ab86fa3416b9":{
          "scriptId":"u38"},
        "2a2b391c7200447289083e1804d73fe9":{
          "scriptId":"u39"},
        "04f14d1465ba4288b4681cc7bfffc7f5":{
          "scriptId":"u40"},
        "af5df1eb0271409da378d631ee6eea35":{
          "scriptId":"u41"},
        "a2ff4b62f33049e78d12a1c7fe988137":{
          "scriptId":"u42"},
        "195816fd62604e789555474ab2c2cc4f":{
          "scriptId":"u43"}},
      "c30d817f6032488595406f350ca406e6":{
        "scriptId":"u44"},
      "302f1fdd803c4ab98a96d23348f022f6":{
        "scriptId":"u45"},
      "b0456e8008f243d3b6abbf2899dd0696":{
        "scriptId":"u46"},
      "f9605511848647c9bc4e38816b381f4e":{
        "scriptId":"u47"}},
    "9bbbc7df2f914ebb97fa25e86d485422":{
      "scriptId":"u48"},
    "f14b6c0b6d6548baa4bd5f7d1e74fbfe":{
      "scriptId":"u49"},
    "516a13ddffe54a27b88890f389b2f6b5":{
      "scriptId":"u50"},
    "0f99bfa83f5e480aa16cb72d44d2f73b":{
      "scriptId":"u51"},
    "a2f2bae13c804440a84d158d072cb894":{
      "scriptId":"u52"},
    "faa76557933448beb8eeb0b528544509":{
      "scriptId":"u53"},
    "98aedd55de084a1db452bc6658be0c35":{
      "scriptId":"u54"},
    "e39f39f979974171a831c0f7751e4030":{
      "scriptId":"u55"},
    "c845d69664eb4da3978bdbf05a6ee774":{
      "scriptId":"u56"},
    "c29241f9f3d641d89af4dde91acbd306":{
      "scriptId":"u57"},
    "73fd4333bbff4c57b22a9de0adbee3e5":{
      "scriptId":"u58"},
    "1ac18b10fb544f429f62c5821f4707a0":{
      "scriptId":"u59"},
    "8a883bdacc8541ef8ae0e070e94579df":{
      "scriptId":"u60"},
    "2cba1486678f435493abf6f1236579fb":{
      "scriptId":"u61"},
    "f3efa429403a4cfe9dd4f6d3ec566baa":{
      "scriptId":"u62"},
    "bf53e3928a144bc4b5c9610eb098f648":{
      "scriptId":"u63"},
    "fc3a9ea00b624c818cf2558bde102361":{
      "scriptId":"u64"},
    "18fb35417b2e4349b0ec14ea71163397":{
      "scriptId":"u65"},
    "4a8c2ed96ea140e4b027d814a7dcc7e4":{
      "scriptId":"u66"},
    "27826213702147bd8ba5eefaf1365751":{
      "scriptId":"u67"},
    "e71e3d574a1b4aa9a9e545c624dac852":{
      "scriptId":"u68"},
    "aace474968c446aba0f9bb391d42f4c0":{
      "scriptId":"u69"},
    "a8e626f11dbd414e89ccb3c2ee97666d":{
      "scriptId":"u70"},
    "576a2c0b00f3405ca8742369275139ff":{
      "scriptId":"u71"},
    "2e36d68e70e54fe98bfa847513fef9a8":{
      "scriptId":"u72"},
    "9417bcfa8a414f1e8c7444d4e1f95cc6":{
      "scriptId":"u73"},
    "4a81bcf15460472ba5974c67e14b2ca0":{
      "scriptId":"u74",
      "b0ad981943d64ab590a2912ed96c062f":{
        "scriptId":"u75"},
      "58e4ffa8ef6b45f0b8a92544a70dd660":{
        "scriptId":"u76"}},
    "93108d742d784a44a86367d0423d8164":{
      "scriptId":"u77"},
    "07f88094eafd4184a913266fcaff3242":{
      "scriptId":"u78"},
    "021b8cea7b42417292375277cb5668bf":{
      "scriptId":"u79"},
    "e11b632105e544b082141de6edd94470":{
      "scriptId":"u80"},
    "c1eb05bc08f34e46ad8d73f0b6484f58":{
      "scriptId":"u81"},
    "212b7da4512a48378d273c25c5792b68":{
      "scriptId":"u82"},
    "90701e56b99746a8bbdfdabcb192bfa4":{
      "scriptId":"u83"},
    "e628a443f0d246d8a62f1334020b436e":{
      "scriptId":"u84"},
    "f4eb1ed6ceb441969aa73133d8232d40":{
      "scriptId":"u85"},
    "35f0a25d3f99437e92c6bf961dbf0a19":{
      "scriptId":"u86"}}});