$axure.loadCurrentPage({
  "url":"friend_list.html",
  "generationDate":new Date(1395042112769.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"72d91c4e89984f1fae29e92a31e241b5",
    "type":"Axure:Page",
    "name":"Friend List",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89c5420ddf1d4b4eabcb964348f552aa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"1a83fe49158f41059f9cd9ac5915885f"},
{
          "id":"27186d48281b4eccbc1395397ccf97cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":105},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9660d7e7a25448d86fe7ad02bed37a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":105},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81540cd18a8442a8f2d3e6118f39e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":150},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"052bc471d7764f9882ce6d8dba94fe2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":150},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c964ae81d044239ffb33c3194cf32d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":195},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d121cf937ce443548d1f135a20d2a8fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":195},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2da06a175384783be6d3709a1833d2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":240},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731c0432448442c98062840359adb399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":240},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69a268b37ad0480da289fde1f4cd9593",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":285},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b52b36f861cf448a910c4eb240f06a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":285},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7c20d61c92a41cb8ac0390dc6428275",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":330},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702c2fbddd474c6bbf7b79947729ed51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":330},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4db4bddbb2b546f8a83fe7c724877409",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":50,
              "y":375},
            "size":{
              "width":670,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d970987d5f4c459b5f9062b8ac7140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":375},
                "size":{
                  "width":670,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be03b1bb13de48a9855564b04c105565",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":50,
              "y":118},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c4028657904e418a71906d4f350854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":50,
                  "y":118},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u62.png"}},
{
          "id":"26da544d11244455b6e45bf2ecfa66fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":50,
              "y":162},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367e952eb4724681b1c45cc8242176e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":50,
                  "y":162},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u62.png"}},
{
          "id":"8576b74d096d4dc8ae853fce73ace08b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":50,
              "y":252},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d2c4849d6f442381d627167079e9ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":50,
                  "y":252},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u62.png"}},
{
          "id":"06a0b86524094831a08e6b648569d5ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":50,
              "y":388},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6696ca87eeef44078589b8fbcde6dcf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":50,
                  "y":388},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u62.png"}},
{
          "id":"a180f6fa2ccf484389b2d620e442263e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":114},
            "size":{
              "width":25,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73dd096eea024aafa069e67ef30bd5e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":114},
                "size":{
                  "width":25,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Single User Chat in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"single_user_chat.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"40b81da576df43eeb3773f207254e98e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":160},
            "size":{
              "width":25,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c998d674a25a49478463dc4e9f6ab276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":160},
                "size":{
                  "width":25,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"f00bbe690b2a4695be0e102add961b7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":204},
            "size":{
              "width":24,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb14cc045bbf4c0aa8b8ac62ae4f8382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":204},
                "size":{
                  "width":24,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"b9034be5e0af438496659afbaf5bfdc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":249},
            "size":{
              "width":25,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b25e0f0163c46cdb0f3034cfc4c3f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":249},
                "size":{
                  "width":25,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"6a766491d51e486180361ffa372744de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":294},
            "size":{
              "width":24,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e48ffe7ada64d2fa8beac25caa0655c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":294},
                "size":{
                  "width":24,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"8b115fc849de4e39b8af917b6828496c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":340},
            "size":{
              "width":24,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fae5615526fa40bd8f163d2677a237eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":340},
                "size":{
                  "width":24,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"a53fa5dc51384f349306a70cd12a31f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":385},
            "size":{
              "width":25,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad29a4036bd43b798d087392d127638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":385},
                "size":{
                  "width":25,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u70.png"}},
{
          "id":"ee55e809d8df42edb48ff2f9a2a0b4f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":113},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3ef90e66be4157b8d9d721fd8a3d37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":113},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"24052073e411446f95d24151a717bb26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":158},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95dbee6fb5fc47f4b6ed5e552a675efd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":158},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"24d932fed44c420cb26efe5eea2006b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":204},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c5cc635e0134208bd694c20c8b682d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":204},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"19210f80d2ee479797bdeeb6f4246dd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":248},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb97effe0dac41ce92b2cd0aaf794e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":248},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"900b28bfad4c4ec4852efa9ace22a655",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":294},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f24b8be1c21644a5b1d95bf53286f7c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":294},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"b7fa37731ca24b3d8c72fc72772492b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":340},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc425d2075543f883de9eccbcaa2fdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":340},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"38401965dee4466197c15a7f6fb3af80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":383},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225e8a82ef514a519761e04c849b3449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":383},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/friend_list/u84.png"}},
{
          "id":"6ae8bf71771e4ce48e1be2dce1fe7087",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"284d1c816a5d467c89662c3cc56765be"},
{
          "id":"099edf80cdb543919d2819b897763027",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":140},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}},
{
          "id":"890aa5c539094140962742ac2999b4d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":188},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}},
{
          "id":"6d94c52bc7344539b8913ca959c689e1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":233},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}},
{
          "id":"951c02063b0e4fb1992315569958f294",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":275},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}},
{
          "id":"cb782dd5c5bb47cfb1bed56b8f51ec3a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":320},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}},
{
          "id":"9660897486e44e6bbef21b80ff112bdf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":365},
            "size":{
              "width":660,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/friend_list/u101_line.png"}}]}},
  "masters":{
    "1a83fe49158f41059f9cd9ac5915885f":{
      "packageId":"1a83fe49158f41059f9cd9ac5915885f",
      "type":"Axure:Master",
      "name":"Popup",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"13a7bd5da3e54308b6fca80087f9b4b1",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"937f1060be994331af4574941a5fe12f"},
{
            "id":"c30d817f6032488595406f350ca406e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":70},
              "size":{
                "width":760,
                "height":510},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"302f1fdd803c4ab98a96d23348f022f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":70},
                  "size":{
                    "width":760,
                    "height":510},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/event_list/u44.png"}},
{
            "id":"b0456e8008f243d3b6abbf2899dd0696",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":750,
                "y":70},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9605511848647c9bc4e38816b381f4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":750,
                    "y":70},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/event_list/u46.png"}}]}},
    "937f1060be994331af4574941a5fe12f":{
      "packageId":"937f1060be994331af4574941a5fe12f",
      "type":"Axure:Master",
      "name":"Home Screen",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c4cb6a00a86f43f4bcc0ef8c413442ab",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
            "id":"1e1186e7b2c94b6d9ad8ebbebfa093fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":345,
                "y":71},
              "size":{
                "width":110,
                "height":499},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9997acae723b49f99ca6b328071cc49a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":345,
                    "y":71},
                  "size":{
                    "width":110,
                    "height":499},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"0ac2936106af46658b63f3af3f1b688e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":170},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa30f9c5eb0a47f39ba133d861111634",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":170},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"b7b24062c1b248889e6c94f3b3c4e563",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":410},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f1fafef5cb4f40609d84800a8a759ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":410},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"5b6e84b065094b50954874095f65ca55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8e922ba8abe4dd888a162d96a5676a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"2f69187aaf56454d888631165e89433c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"838a13adcb2c4760879131c11a1d1308",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"89b47eb9cbd34f71afefec2bbbe6221a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"909526bc04c54e17913d83a5915d018c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"e7cc05c8b6d9497e9033bbc715aa05f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed00e4773ff64e6b81cf9daa624ba342",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"20309fb5c652419eaa1378a33aba38e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"64b7158854944bf292ca143f00d38f64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"452bb3de4d174450bc013c78e9312636",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a8f3d9d82354fc5be64b00c09bc99b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6463cb28a52941fbaf67e74bf36c093b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bbf091a8aae6434db2c20f9d16089409",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"65dc6ea3c2bc45e9bd903a8337420258",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47b8ab617fbf441b9dcdf907c3f15359",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"01d0201b24864181b86f93aa996a909c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"6fce1fcbd7b74a4fa90a699ee160c776"},
{
            "id":"a9e437461ac34e60a97d7ed400848015",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28637fe8e56f4d21a32304eb74b917cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"20f64c2556174e258c98ab86fa3416b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a2b391c7200447289083e1804d73fe9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"04f14d1465ba4288b4681cc7bfffc7f5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af5df1eb0271409da378d631ee6eea35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a2ff4b62f33049e78d12a1c7fe988137",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"195816fd62604e789555474ab2c2cc4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}},
    "6fce1fcbd7b74a4fa90a699ee160c776":{
      "packageId":"6fce1fcbd7b74a4fa90a699ee160c776",
      "type":"Axure:Master",
      "name":"Top Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1fc2d5a32fc04aee8625a29e1baeccac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f728946738cc43f8a3e29348456955bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"888b1d943b4e4702836e8be23c5c2192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cafb9e688c2244f59a4523ca4599f297",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"98153c8ab8b44e13b4b8e2e3f725fd83",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc399042f0b4b1f9aca768cc4b218cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"15e4f70427624088850f7ffe1b5bd001",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2efb20853bc34548abdd42d7e54c25b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}}]}},
    "284d1c816a5d467c89662c3cc56765be":{
      "packageId":"284d1c816a5d467c89662c3cc56765be",
      "type":"Axure:Master",
      "name":"Friends Button Active",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c6599aca0bd947ca83d71cbb1619f6f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99da7925d5b44d3ba1e6552dcccbbc4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u44.png"}}]}}},
  "objectPaths":{
    "89c5420ddf1d4b4eabcb964348f552aa":{
      "scriptId":"u0",
      "13a7bd5da3e54308b6fca80087f9b4b1":{
        "scriptId":"u1",
        "c4cb6a00a86f43f4bcc0ef8c413442ab":{
          "scriptId":"u2",
          "89ad40f4e4a845958f4f199ffc29cccd":{
            "scriptId":"u3"},
          "817028217dd1407aa5e9ad17a76d4c45":{
            "scriptId":"u4"}},
        "1e1186e7b2c94b6d9ad8ebbebfa093fd":{
          "scriptId":"u5"},
        "9997acae723b49f99ca6b328071cc49a":{
          "scriptId":"u6"},
        "0ac2936106af46658b63f3af3f1b688e":{
          "scriptId":"u7"},
        "aa30f9c5eb0a47f39ba133d861111634":{
          "scriptId":"u8"},
        "b7b24062c1b248889e6c94f3b3c4e563":{
          "scriptId":"u9"},
        "f1fafef5cb4f40609d84800a8a759ef4":{
          "scriptId":"u10"},
        "5b6e84b065094b50954874095f65ca55":{
          "scriptId":"u11"},
        "f8e922ba8abe4dd888a162d96a5676a1":{
          "scriptId":"u12"},
        "2f69187aaf56454d888631165e89433c":{
          "scriptId":"u13"},
        "838a13adcb2c4760879131c11a1d1308":{
          "scriptId":"u14"},
        "89b47eb9cbd34f71afefec2bbbe6221a":{
          "scriptId":"u15"},
        "909526bc04c54e17913d83a5915d018c":{
          "scriptId":"u16"},
        "e7cc05c8b6d9497e9033bbc715aa05f9":{
          "scriptId":"u17"},
        "ed00e4773ff64e6b81cf9daa624ba342":{
          "scriptId":"u18"},
        "20309fb5c652419eaa1378a33aba38e3":{
          "scriptId":"u19"},
        "64b7158854944bf292ca143f00d38f64":{
          "scriptId":"u20"},
        "452bb3de4d174450bc013c78e9312636":{
          "scriptId":"u21"},
        "1a8f3d9d82354fc5be64b00c09bc99b1":{
          "scriptId":"u22"},
        "6463cb28a52941fbaf67e74bf36c093b":{
          "scriptId":"u23"},
        "bbf091a8aae6434db2c20f9d16089409":{
          "scriptId":"u24"},
        "65dc6ea3c2bc45e9bd903a8337420258":{
          "scriptId":"u25"},
        "47b8ab617fbf441b9dcdf907c3f15359":{
          "scriptId":"u26"},
        "01d0201b24864181b86f93aa996a909c":{
          "scriptId":"u27",
          "1fc2d5a32fc04aee8625a29e1baeccac":{
            "scriptId":"u28"},
          "f728946738cc43f8a3e29348456955bc":{
            "scriptId":"u29"},
          "888b1d943b4e4702836e8be23c5c2192":{
            "scriptId":"u30"},
          "cafb9e688c2244f59a4523ca4599f297":{
            "scriptId":"u31"},
          "98153c8ab8b44e13b4b8e2e3f725fd83":{
            "scriptId":"u32"},
          "cfc399042f0b4b1f9aca768cc4b218cb":{
            "scriptId":"u33"},
          "15e4f70427624088850f7ffe1b5bd001":{
            "scriptId":"u34"},
          "2efb20853bc34548abdd42d7e54c25b3":{
            "scriptId":"u35"}},
        "a9e437461ac34e60a97d7ed400848015":{
          "scriptId":"u36"},
        "28637fe8e56f4d21a32304eb74b917cb":{
          "scriptId":"u37"},
        "20f64c2556174e258c98ab86fa3416b9":{
          "scriptId":"u38"},
        "2a2b391c7200447289083e1804d73fe9":{
          "scriptId":"u39"},
        "04f14d1465ba4288b4681cc7bfffc7f5":{
          "scriptId":"u40"},
        "af5df1eb0271409da378d631ee6eea35":{
          "scriptId":"u41"},
        "a2ff4b62f33049e78d12a1c7fe988137":{
          "scriptId":"u42"},
        "195816fd62604e789555474ab2c2cc4f":{
          "scriptId":"u43"}},
      "c30d817f6032488595406f350ca406e6":{
        "scriptId":"u44"},
      "302f1fdd803c4ab98a96d23348f022f6":{
        "scriptId":"u45"},
      "b0456e8008f243d3b6abbf2899dd0696":{
        "scriptId":"u46"},
      "f9605511848647c9bc4e38816b381f4e":{
        "scriptId":"u47"}},
    "27186d48281b4eccbc1395397ccf97cf":{
      "scriptId":"u48"},
    "f9660d7e7a25448d86fe7ad02bed37a7":{
      "scriptId":"u49"},
    "f81540cd18a8442a8f2d3e6118f39e08":{
      "scriptId":"u50"},
    "052bc471d7764f9882ce6d8dba94fe2c":{
      "scriptId":"u51"},
    "f0c964ae81d044239ffb33c3194cf32d":{
      "scriptId":"u52"},
    "d121cf937ce443548d1f135a20d2a8fb":{
      "scriptId":"u53"},
    "a2da06a175384783be6d3709a1833d2d":{
      "scriptId":"u54"},
    "731c0432448442c98062840359adb399":{
      "scriptId":"u55"},
    "69a268b37ad0480da289fde1f4cd9593":{
      "scriptId":"u56"},
    "b52b36f861cf448a910c4eb240f06a8b":{
      "scriptId":"u57"},
    "f7c20d61c92a41cb8ac0390dc6428275":{
      "scriptId":"u58"},
    "702c2fbddd474c6bbf7b79947729ed51":{
      "scriptId":"u59"},
    "4db4bddbb2b546f8a83fe7c724877409":{
      "scriptId":"u60"},
    "a8d970987d5f4c459b5f9062b8ac7140":{
      "scriptId":"u61"},
    "be03b1bb13de48a9855564b04c105565":{
      "scriptId":"u62"},
    "32c4028657904e418a71906d4f350854":{
      "scriptId":"u63"},
    "26da544d11244455b6e45bf2ecfa66fe":{
      "scriptId":"u64"},
    "367e952eb4724681b1c45cc8242176e2":{
      "scriptId":"u65"},
    "8576b74d096d4dc8ae853fce73ace08b":{
      "scriptId":"u66"},
    "01d2c4849d6f442381d627167079e9ff":{
      "scriptId":"u67"},
    "06a0b86524094831a08e6b648569d5ba":{
      "scriptId":"u68"},
    "6696ca87eeef44078589b8fbcde6dcf8":{
      "scriptId":"u69"},
    "a180f6fa2ccf484389b2d620e442263e":{
      "scriptId":"u70"},
    "73dd096eea024aafa069e67ef30bd5e2":{
      "scriptId":"u71"},
    "40b81da576df43eeb3773f207254e98e":{
      "scriptId":"u72"},
    "c998d674a25a49478463dc4e9f6ab276":{
      "scriptId":"u73"},
    "f00bbe690b2a4695be0e102add961b7c":{
      "scriptId":"u74"},
    "fb14cc045bbf4c0aa8b8ac62ae4f8382":{
      "scriptId":"u75"},
    "b9034be5e0af438496659afbaf5bfdc0":{
      "scriptId":"u76"},
    "1b25e0f0163c46cdb0f3034cfc4c3f21":{
      "scriptId":"u77"},
    "6a766491d51e486180361ffa372744de":{
      "scriptId":"u78"},
    "5e48ffe7ada64d2fa8beac25caa0655c":{
      "scriptId":"u79"},
    "8b115fc849de4e39b8af917b6828496c":{
      "scriptId":"u80"},
    "fae5615526fa40bd8f163d2677a237eb":{
      "scriptId":"u81"},
    "a53fa5dc51384f349306a70cd12a31f4":{
      "scriptId":"u82"},
    "9ad29a4036bd43b798d087392d127638":{
      "scriptId":"u83"},
    "ee55e809d8df42edb48ff2f9a2a0b4f6":{
      "scriptId":"u84"},
    "8c3ef90e66be4157b8d9d721fd8a3d37":{
      "scriptId":"u85"},
    "24052073e411446f95d24151a717bb26":{
      "scriptId":"u86"},
    "95dbee6fb5fc47f4b6ed5e552a675efd":{
      "scriptId":"u87"},
    "24d932fed44c420cb26efe5eea2006b1":{
      "scriptId":"u88"},
    "9c5cc635e0134208bd694c20c8b682d5":{
      "scriptId":"u89"},
    "19210f80d2ee479797bdeeb6f4246dd8":{
      "scriptId":"u90"},
    "fb97effe0dac41ce92b2cd0aaf794e11":{
      "scriptId":"u91"},
    "900b28bfad4c4ec4852efa9ace22a655":{
      "scriptId":"u92"},
    "f24b8be1c21644a5b1d95bf53286f7c8":{
      "scriptId":"u93"},
    "b7fa37731ca24b3d8c72fc72772492b0":{
      "scriptId":"u94"},
    "5fc425d2075543f883de9eccbcaa2fdb":{
      "scriptId":"u95"},
    "38401965dee4466197c15a7f6fb3af80":{
      "scriptId":"u96"},
    "225e8a82ef514a519761e04c849b3449":{
      "scriptId":"u97"},
    "6ae8bf71771e4ce48e1be2dce1fe7087":{
      "scriptId":"u98",
      "c6599aca0bd947ca83d71cbb1619f6f8":{
        "scriptId":"u99"},
      "99da7925d5b44d3ba1e6552dcccbbc4f":{
        "scriptId":"u100"}},
    "099edf80cdb543919d2819b897763027":{
      "scriptId":"u101"},
    "890aa5c539094140962742ac2999b4d9":{
      "scriptId":"u102"},
    "6d94c52bc7344539b8913ca959c689e1":{
      "scriptId":"u103"},
    "951c02063b0e4fb1992315569958f294":{
      "scriptId":"u104"},
    "cb782dd5c5bb47cfb1bed56b8f51ec3a":{
      "scriptId":"u105"},
    "9660897486e44e6bbef21b80ff112bdf":{
      "scriptId":"u106"}}});