$axure.loadCurrentPage({
  "url":"single_user_chat.html",
  "generationDate":new Date(1395042112963.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"553abc9d0a7840a2848720b643322c21",
    "type":"Axure:Page",
    "name":"Single User Chat",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b0bf451f82147119dc944be88befad1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"1a83fe49158f41059f9cd9ac5915885f"},
{
          "id":"ba7246cac3bf4123973b7fff024dec70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad2c8aba1f44666acb61a660ff41e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":50,
                  "y":100},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event_list/u48.png"}},
{
          "id":"e650c7455be445998cca722fb202a03e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":60,
              "y":160},
            "size":{
              "width":330,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d0d1eb1af114cf1b6addcef8a46c654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":60,
                  "y":160},
                "size":{
                  "width":330,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/single_user_chat/u50.png"}},
{
          "id":"6699fcd5b087479db21f4b846efbf0c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":220},
            "size":{
              "width":330,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8cdbf0e3d8407495f241fc909e3d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":220},
                "size":{
                  "width":330,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/single_user_chat/u52.png"}},
{
          "id":"7af17019368c4eaba6d3eaab882fcb5b",
          "label":"newMessageText",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":60,
              "y":445},
            "size":{
              "width":610,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"014008b89bb34eca9e4eebc0563579c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":60,
              "y":280},
            "size":{
              "width":330,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"920db0331805414b8ee9ea44dc60f0c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":60,
                  "y":280},
                "size":{
                  "width":330,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/single_user_chat/u50.png"}},
{
          "id":"8a408013a8b749d0973a408deb3d8f4a",
          "label":"submitButton",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":680,
              "y":450},
            "size":{
              "width":60,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c4904bbb81493db5485f26639299ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":680,
                  "y":450},
                "size":{
                  "width":60,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Send Non-Blank Message<br> (If text on newMessageText does not equal &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["7af17019368c4eaba6d3eaab882fcb5b"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on messageText equal to text on newMessageText",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["959c7506315046d0a54f05e19cbe3575"]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["7af17019368c4eaba6d3eaab882fcb5b"]}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show messageBubble,<br>messageText",
                      "objectsToFades":[{
                          "objectPath":["a49e405067b44c94974a3903a630952a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["52142e6e4b6a4d23a8823032dd97f79b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFunction",
                      "description":"Set text on newMessageText equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7af17019368c4eaba6d3eaab882fcb5b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/single_user_chat/submitbutton_u57.png"}},
{
          "id":"cd4ad4beac9043e38b3a24d30484a23a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":79,
              "y":170},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc1ea4fe664e4f649545a020f09783dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":170},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c77ca334c9eb4a2680870869e8f7dfcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":359,
              "y":230},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1bd903cbd646a4bd1c9f82b77e0ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":230},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34deebd195e843868c72ba7b75802c49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":79,
              "y":290},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649c9337629e41589a360fde7b541838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":290},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f0b7e648e6d4ba2b3b58ddbb7bd0d15",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"284d1c816a5d467c89662c3cc56765be"},
{
          "id":"a49e405067b44c94974a3903a630952a",
          "label":"messageBubble",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":340,
              "y":340},
            "size":{
              "width":330,
              "height":60},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e166030883a14567b2a345e230b4b53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":340,
                  "y":340},
                "size":{
                  "width":330,
                  "height":60},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/single_user_chat/u52.png"}},
{
          "id":"52142e6e4b6a4d23a8823032dd97f79b",
          "label":"messageText",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":359,
              "y":350},
            "size":{
              "width":292,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"959c7506315046d0a54f05e19cbe3575",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":350},
                "size":{
                  "width":292,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "1a83fe49158f41059f9cd9ac5915885f":{
      "packageId":"1a83fe49158f41059f9cd9ac5915885f",
      "type":"Axure:Master",
      "name":"Popup",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"13a7bd5da3e54308b6fca80087f9b4b1",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"937f1060be994331af4574941a5fe12f"},
{
            "id":"c30d817f6032488595406f350ca406e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":70},
              "size":{
                "width":760,
                "height":510},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"302f1fdd803c4ab98a96d23348f022f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":70},
                  "size":{
                    "width":760,
                    "height":510},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/event_list/u44.png"}},
{
            "id":"b0456e8008f243d3b6abbf2899dd0696",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":750,
                "y":70},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f9605511848647c9bc4e38816b381f4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":750,
                    "y":70},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/event_list/u46.png"}}]}},
    "937f1060be994331af4574941a5fe12f":{
      "packageId":"937f1060be994331af4574941a5fe12f",
      "type":"Axure:Master",
      "name":"Home Screen",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c4cb6a00a86f43f4bcc0ef8c413442ab",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
            "id":"1e1186e7b2c94b6d9ad8ebbebfa093fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":345,
                "y":71},
              "size":{
                "width":110,
                "height":499},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9997acae723b49f99ca6b328071cc49a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":345,
                    "y":71},
                  "size":{
                    "width":110,
                    "height":499},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"0ac2936106af46658b63f3af3f1b688e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":170},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa30f9c5eb0a47f39ba133d861111634",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":170},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"b7b24062c1b248889e6c94f3b3c4e563",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8396C4},
              "location":{
                "x":218,
                "y":410},
              "size":{
                "width":363,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f1fafef5cb4f40609d84800a8a759ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8396C4},
                  "location":{
                    "x":218,
                    "y":410},
                  "size":{
                    "width":363,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u6.png"}},
{
            "id":"5b6e84b065094b50954874095f65ca55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8e922ba8abe4dd888a162d96a5676a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"2f69187aaf56454d888631165e89433c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":600,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"838a13adcb2c4760879131c11a1d1308",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":600,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"89b47eb9cbd34f71afefec2bbbe6221a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":128},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"909526bc04c54e17913d83a5915d018c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":128},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"e7cc05c8b6d9497e9033bbc715aa05f9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":70,
                "y":368},
              "size":{
                "width":131,
                "height":135}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed00e4773ff64e6b81cf9daa624ba342",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":70,
                    "y":368},
                  "size":{
                    "width":131,
                    "height":135}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u10.png"}},
{
            "id":"20309fb5c652419eaa1378a33aba38e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"64b7158854944bf292ca143f00d38f64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"452bb3de4d174450bc013c78e9312636",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":620,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a8f3d9d82354fc5be64b00c09bc99b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":620,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6463cb28a52941fbaf67e74bf36c093b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":170},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bbf091a8aae6434db2c20f9d16089409",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":170},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"65dc6ea3c2bc45e9bd903a8337420258",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":90,
                "y":410},
              "size":{
                "width":90,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47b8ab617fbf441b9dcdf907c3f15359",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":410},
                  "size":{
                    "width":90,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"01d0201b24864181b86f93aa996a909c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"6fce1fcbd7b74a4fa90a699ee160c776"},
{
            "id":"a9e437461ac34e60a97d7ed400848015",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28637fe8e56f4d21a32304eb74b917cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"20f64c2556174e258c98ab86fa3416b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":240},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a2b391c7200447289083e1804d73fe9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":240},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Coffee Shop in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"coffee_shop.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"04f14d1465ba4288b4681cc7bfffc7f5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":70,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af5df1eb0271409da378d631ee6eea35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a2ff4b62f33049e78d12a1c7fe988137",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":600,
                "y":480},
              "size":{
                "width":131,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"195816fd62604e789555474ab2c2cc4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":480},
                  "size":{
                    "width":131,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}},
    "6fce1fcbd7b74a4fa90a699ee160c776":{
      "packageId":"6fce1fcbd7b74a4fa90a699ee160c776",
      "type":"Axure:Master",
      "name":"Top Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1fc2d5a32fc04aee8625a29e1baeccac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f728946738cc43f8a3e29348456955bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"888b1d943b4e4702836e8be23c5c2192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cafb9e688c2244f59a4523ca4599f297",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"98153c8ab8b44e13b4b8e2e3f725fd83",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc399042f0b4b1f9aca768cc4b218cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"15e4f70427624088850f7ffe1b5bd001",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2efb20853bc34548abdd42d7e54c25b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}}]}},
    "284d1c816a5d467c89662c3cc56765be":{
      "packageId":"284d1c816a5d467c89662c3cc56765be",
      "type":"Axure:Master",
      "name":"Friends Button Active",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c6599aca0bd947ca83d71cbb1619f6f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4965A0},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99da7925d5b44d3ba1e6552dcccbbc4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4965A0},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u44.png"}}]}}},
  "objectPaths":{
    "4b0bf451f82147119dc944be88befad1":{
      "scriptId":"u0",
      "13a7bd5da3e54308b6fca80087f9b4b1":{
        "scriptId":"u1",
        "c4cb6a00a86f43f4bcc0ef8c413442ab":{
          "scriptId":"u2",
          "89ad40f4e4a845958f4f199ffc29cccd":{
            "scriptId":"u3"},
          "817028217dd1407aa5e9ad17a76d4c45":{
            "scriptId":"u4"}},
        "1e1186e7b2c94b6d9ad8ebbebfa093fd":{
          "scriptId":"u5"},
        "9997acae723b49f99ca6b328071cc49a":{
          "scriptId":"u6"},
        "0ac2936106af46658b63f3af3f1b688e":{
          "scriptId":"u7"},
        "aa30f9c5eb0a47f39ba133d861111634":{
          "scriptId":"u8"},
        "b7b24062c1b248889e6c94f3b3c4e563":{
          "scriptId":"u9"},
        "f1fafef5cb4f40609d84800a8a759ef4":{
          "scriptId":"u10"},
        "5b6e84b065094b50954874095f65ca55":{
          "scriptId":"u11"},
        "f8e922ba8abe4dd888a162d96a5676a1":{
          "scriptId":"u12"},
        "2f69187aaf56454d888631165e89433c":{
          "scriptId":"u13"},
        "838a13adcb2c4760879131c11a1d1308":{
          "scriptId":"u14"},
        "89b47eb9cbd34f71afefec2bbbe6221a":{
          "scriptId":"u15"},
        "909526bc04c54e17913d83a5915d018c":{
          "scriptId":"u16"},
        "e7cc05c8b6d9497e9033bbc715aa05f9":{
          "scriptId":"u17"},
        "ed00e4773ff64e6b81cf9daa624ba342":{
          "scriptId":"u18"},
        "20309fb5c652419eaa1378a33aba38e3":{
          "scriptId":"u19"},
        "64b7158854944bf292ca143f00d38f64":{
          "scriptId":"u20"},
        "452bb3de4d174450bc013c78e9312636":{
          "scriptId":"u21"},
        "1a8f3d9d82354fc5be64b00c09bc99b1":{
          "scriptId":"u22"},
        "6463cb28a52941fbaf67e74bf36c093b":{
          "scriptId":"u23"},
        "bbf091a8aae6434db2c20f9d16089409":{
          "scriptId":"u24"},
        "65dc6ea3c2bc45e9bd903a8337420258":{
          "scriptId":"u25"},
        "47b8ab617fbf441b9dcdf907c3f15359":{
          "scriptId":"u26"},
        "01d0201b24864181b86f93aa996a909c":{
          "scriptId":"u27",
          "1fc2d5a32fc04aee8625a29e1baeccac":{
            "scriptId":"u28"},
          "f728946738cc43f8a3e29348456955bc":{
            "scriptId":"u29"},
          "888b1d943b4e4702836e8be23c5c2192":{
            "scriptId":"u30"},
          "cafb9e688c2244f59a4523ca4599f297":{
            "scriptId":"u31"},
          "98153c8ab8b44e13b4b8e2e3f725fd83":{
            "scriptId":"u32"},
          "cfc399042f0b4b1f9aca768cc4b218cb":{
            "scriptId":"u33"},
          "15e4f70427624088850f7ffe1b5bd001":{
            "scriptId":"u34"},
          "2efb20853bc34548abdd42d7e54c25b3":{
            "scriptId":"u35"}},
        "a9e437461ac34e60a97d7ed400848015":{
          "scriptId":"u36"},
        "28637fe8e56f4d21a32304eb74b917cb":{
          "scriptId":"u37"},
        "20f64c2556174e258c98ab86fa3416b9":{
          "scriptId":"u38"},
        "2a2b391c7200447289083e1804d73fe9":{
          "scriptId":"u39"},
        "04f14d1465ba4288b4681cc7bfffc7f5":{
          "scriptId":"u40"},
        "af5df1eb0271409da378d631ee6eea35":{
          "scriptId":"u41"},
        "a2ff4b62f33049e78d12a1c7fe988137":{
          "scriptId":"u42"},
        "195816fd62604e789555474ab2c2cc4f":{
          "scriptId":"u43"}},
      "c30d817f6032488595406f350ca406e6":{
        "scriptId":"u44"},
      "302f1fdd803c4ab98a96d23348f022f6":{
        "scriptId":"u45"},
      "b0456e8008f243d3b6abbf2899dd0696":{
        "scriptId":"u46"},
      "f9605511848647c9bc4e38816b381f4e":{
        "scriptId":"u47"}},
    "ba7246cac3bf4123973b7fff024dec70":{
      "scriptId":"u48"},
    "2ad2c8aba1f44666acb61a660ff41e31":{
      "scriptId":"u49"},
    "e650c7455be445998cca722fb202a03e":{
      "scriptId":"u50"},
    "5d0d1eb1af114cf1b6addcef8a46c654":{
      "scriptId":"u51"},
    "6699fcd5b087479db21f4b846efbf0c6":{
      "scriptId":"u52"},
    "ed8cdbf0e3d8407495f241fc909e3d76":{
      "scriptId":"u53"},
    "7af17019368c4eaba6d3eaab882fcb5b":{
      "scriptId":"u54"},
    "014008b89bb34eca9e4eebc0563579c1":{
      "scriptId":"u55"},
    "920db0331805414b8ee9ea44dc60f0c4":{
      "scriptId":"u56"},
    "8a408013a8b749d0973a408deb3d8f4a":{
      "scriptId":"u57"},
    "79c4904bbb81493db5485f26639299ac":{
      "scriptId":"u58"},
    "cd4ad4beac9043e38b3a24d30484a23a":{
      "scriptId":"u59"},
    "bc1ea4fe664e4f649545a020f09783dd":{
      "scriptId":"u60"},
    "c77ca334c9eb4a2680870869e8f7dfcf":{
      "scriptId":"u61"},
    "2f1bd903cbd646a4bd1c9f82b77e0ad6":{
      "scriptId":"u62"},
    "34deebd195e843868c72ba7b75802c49":{
      "scriptId":"u63"},
    "649c9337629e41589a360fde7b541838":{
      "scriptId":"u64"},
    "8f0b7e648e6d4ba2b3b58ddbb7bd0d15":{
      "scriptId":"u65",
      "c6599aca0bd947ca83d71cbb1619f6f8":{
        "scriptId":"u66"},
      "99da7925d5b44d3ba1e6552dcccbbc4f":{
        "scriptId":"u67"}},
    "a49e405067b44c94974a3903a630952a":{
      "scriptId":"u68"},
    "e166030883a14567b2a345e230b4b53b":{
      "scriptId":"u69"},
    "52142e6e4b6a4d23a8823032dd97f79b":{
      "scriptId":"u70"},
    "959c7506315046d0a54f05e19cbe3575":{
      "scriptId":"u71"}}});