$axure.loadCurrentPage({
  "url":"coffee_shop.html",
  "generationDate":new Date(1395042113112.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"3d9593cf2d574313b4e64c38c3108ba4",
    "type":"Axure:Page",
    "name":"Coffee Shop",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3f39050825424f4ea4f8761f8ac301a9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
          "id":"6411b6edb60a4db983e7e0fc40e444ab",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6fce1fcbd7b74a4fa90a699ee160c776"},
{
          "id":"3dd3a6144972468bbd62f2b50a476867",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":270,
              "y":60},
            "size":{
              "width":260,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48caac20fed24897901921176c6c1fb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":270,
                  "y":60},
                "size":{
                  "width":260,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u12.png"}},
{
          "id":"34831c8c36984955ac0b608c6f3c12bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":100,
              "y":170},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6af7d0f186994324bfafd087d0788135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":100,
                  "y":170},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"b3c9b6c4c49c4c739d905fa4d8fc22f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9d4682a811047af8c99fed3bd46e91b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":260,
                  "y":190},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Popup,<br>PopupButton",
                      "objectsToFades":[{
                          "objectPath":["f3a0d1559b0f40e6aaba0470f9740e23"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0bcf4c02aa84400f9d89e7284ad2214e"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"99ee346e163342af8d88a9df15ccb509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":300,
              "y":380},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ead5391e284e9e8965aa0f72700593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":300,
                  "y":380},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"1d304b91b8324cb0a6e8b0fc4cc9dfd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":430,
              "y":490},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e60808cb56e4675a1feb385cfb05a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":430,
                  "y":490},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"f3a2db898b2e4b538fe33f50f60d3cef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":520,
              "y":210},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb672bc0f66c45689b44dbb77bde6eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":520,
                  "y":210},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"15c2417950bc4dd5ac64e1ee882f4465",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":690,
              "y":150},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109d65c8fb4a4a689dafbd76792f2057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":690,
                  "y":150},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u14.png"}},
{
          "id":"df4e0be96a21416d91cd98f4db51a2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":10,
              "y":560},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97262867400049bbb9fa4a67c67a0d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":10,
                  "y":560},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop/u26.png"}},
{
          "id":"f3a0d1559b0f40e6aaba0470f9740e23",
          "label":"Popup",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "paddingTop":"15",
            "location":{
              "x":320,
              "y":110},
            "size":{
              "width":180,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ec855b18dc4e749eec46ed099d8c40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "paddingTop":"15",
                "location":{
                  "x":320,
                  "y":110},
                "size":{
                  "width":180,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/popup_u28.png"}},
{
          "id":"0bcf4c02aa84400f9d89e7284ad2214e",
          "label":"PopupButton",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4965A0},
            "location":{
              "x":340,
              "y":170},
            "size":{
              "width":140,
              "height":30},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de8396a86b664e1e8bd47e050e4c906c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4965A0},
                "location":{
                  "x":340,
                  "y":170},
                "size":{
                  "width":140,
                  "height":30},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Coffee Shop Chat in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"coffee_shop_chat.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop/popupbutton_u30.png"}},
{
          "id":"52cb66be051c41a69899e08c940feff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":160,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e8d4806fb6c402bb55adbfc74f065e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":160,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u32.png"}},
{
          "id":"10bac90c4f3e48c98d24a2cce4377a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":320,
              "y":370},
            "size":{
              "width":160,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"201378aa817844b380e3ba269a23d02a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":320,
                  "y":370},
                "size":{
                  "width":160,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u34.png"}},
{
          "id":"7dba9a97da4748ee8bdba219b3df16bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":550,
              "y":130},
            "size":{
              "width":160,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2c112d582746b3a258ef97d7ee9cb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":550,
                  "y":130},
                "size":{
                  "width":160,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop/u36.png"}}]}},
  "masters":{
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}},
    "6fce1fcbd7b74a4fa90a699ee160c776":{
      "packageId":"6fce1fcbd7b74a4fa90a699ee160c776",
      "type":"Axure:Master",
      "name":"Top Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1fc2d5a32fc04aee8625a29e1baeccac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f728946738cc43f8a3e29348456955bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"888b1d943b4e4702836e8be23c5c2192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cafb9e688c2244f59a4523ca4599f297",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"98153c8ab8b44e13b4b8e2e3f725fd83",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc399042f0b4b1f9aca768cc4b218cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"15e4f70427624088850f7ffe1b5bd001",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2efb20853bc34548abdd42d7e54c25b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}}]}}},
  "objectPaths":{
    "3f39050825424f4ea4f8761f8ac301a9":{
      "scriptId":"u0",
      "89ad40f4e4a845958f4f199ffc29cccd":{
        "scriptId":"u1"},
      "817028217dd1407aa5e9ad17a76d4c45":{
        "scriptId":"u2"}},
    "6411b6edb60a4db983e7e0fc40e444ab":{
      "scriptId":"u3",
      "1fc2d5a32fc04aee8625a29e1baeccac":{
        "scriptId":"u4"},
      "f728946738cc43f8a3e29348456955bc":{
        "scriptId":"u5"},
      "888b1d943b4e4702836e8be23c5c2192":{
        "scriptId":"u6"},
      "cafb9e688c2244f59a4523ca4599f297":{
        "scriptId":"u7"},
      "98153c8ab8b44e13b4b8e2e3f725fd83":{
        "scriptId":"u8"},
      "cfc399042f0b4b1f9aca768cc4b218cb":{
        "scriptId":"u9"},
      "15e4f70427624088850f7ffe1b5bd001":{
        "scriptId":"u10"},
      "2efb20853bc34548abdd42d7e54c25b3":{
        "scriptId":"u11"}},
    "3dd3a6144972468bbd62f2b50a476867":{
      "scriptId":"u12"},
    "48caac20fed24897901921176c6c1fb9":{
      "scriptId":"u13"},
    "34831c8c36984955ac0b608c6f3c12bd":{
      "scriptId":"u14"},
    "6af7d0f186994324bfafd087d0788135":{
      "scriptId":"u15"},
    "b3c9b6c4c49c4c739d905fa4d8fc22f8":{
      "scriptId":"u16"},
    "a9d4682a811047af8c99fed3bd46e91b":{
      "scriptId":"u17"},
    "99ee346e163342af8d88a9df15ccb509":{
      "scriptId":"u18"},
    "25ead5391e284e9e8965aa0f72700593":{
      "scriptId":"u19"},
    "1d304b91b8324cb0a6e8b0fc4cc9dfd1":{
      "scriptId":"u20"},
    "1e60808cb56e4675a1feb385cfb05a62":{
      "scriptId":"u21"},
    "f3a2db898b2e4b538fe33f50f60d3cef":{
      "scriptId":"u22"},
    "cb672bc0f66c45689b44dbb77bde6eba":{
      "scriptId":"u23"},
    "15c2417950bc4dd5ac64e1ee882f4465":{
      "scriptId":"u24"},
    "109d65c8fb4a4a689dafbd76792f2057":{
      "scriptId":"u25"},
    "df4e0be96a21416d91cd98f4db51a2de":{
      "scriptId":"u26"},
    "97262867400049bbb9fa4a67c67a0d2f":{
      "scriptId":"u27"},
    "f3a0d1559b0f40e6aaba0470f9740e23":{
      "scriptId":"u28"},
    "70ec855b18dc4e749eec46ed099d8c40":{
      "scriptId":"u29"},
    "0bcf4c02aa84400f9d89e7284ad2214e":{
      "scriptId":"u30"},
    "de8396a86b664e1e8bd47e050e4c906c":{
      "scriptId":"u31"},
    "52cb66be051c41a69899e08c940feff2":{
      "scriptId":"u32"},
    "5e8d4806fb6c402bb55adbfc74f065e8":{
      "scriptId":"u33"},
    "10bac90c4f3e48c98d24a2cce4377a98":{
      "scriptId":"u34"},
    "201378aa817844b380e3ba269a23d02a":{
      "scriptId":"u35"},
    "7dba9a97da4748ee8bdba219b3df16bb":{
      "scriptId":"u36"},
    "5a2c112d582746b3a258ef97d7ee9cb5":{
      "scriptId":"u37"}}});