$axure.loadCurrentPage({
  "url":"coffee_shop_chat.html",
  "generationDate":new Date(1395042113252.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"message"],
  "page":{
    "packageId":"a1d9b0650d8b40d58aa00273fe93e9aa",
    "type":"Axure:Page",
    "name":"Coffee Shop Chat",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4edc6ffe24154d4f980a050b7fb483d4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f2fb4637bc3044a3a7de746a883444bf"},
{
          "id":"02438f8ca8b04fe0931f2c93ef53cccc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6fce1fcbd7b74a4fa90a699ee160c776"},
{
          "id":"4aa3512d612b4fd2bc67f6f55ba6eed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":100,
              "y":170},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df6c3c2a0094db8a6fb415e983ad2b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":100,
                  "y":170},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u12.png"}},
{
          "id":"7e92fa55bbf043a8896ce4afb4ce866e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8b1bad744394c4b9e7b9b8c0b2dc6ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":260,
                  "y":190},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u12.png"}},
{
          "id":"93ae16b184ac40ce9d595350d0803427",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":160,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39068d8df3f64fafbd18b32ecbc0a7c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":160,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u16.png"}},
{
          "id":"0115aa7cee6f4cc08bd44fb83133a52b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "location":{
              "x":10,
              "y":560},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ae2b5ebcee47f1a15da0c93801c265",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "location":{
                  "x":10,
                  "y":560},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop_chat/u18.png"}},
{
          "id":"16c8b9f240cf47a3858bc319749c78d4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":310},
            "size":{
              "width":471,
              "height":10},
            "rotation":"90",
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/coffee_shop_chat/u20_line.png"}},
{
          "id":"475357ba669f4a68b7bc613bc67ed94b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":415,
              "y":100},
            "size":{
              "width":205,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978e181799314a9abe424215cbb2ba56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":415,
                  "y":100},
                "size":{
                  "width":205,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u21.png"}},
{
          "id":"cff3943629914f87a18f419a24845429",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":180},
            "size":{
              "width":205,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d44de5a2e717446fb07784362eb7087a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":180},
                "size":{
                  "width":205,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u23.png"}},
{
          "id":"2db3f97c078a4e398df7ac26265c3f11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":434,
              "y":110},
            "size":{
              "width":161,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75cf67c1a71d43ccb314d35e3db31d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":110},
                "size":{
                  "width":161,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"506d29e9464f4f7ea23cda4b100b7d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":600,
              "y":190},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f8aba58c44441fab4c048ae36245c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":190},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cff1a13b56ce4a1c94e60fb7f9cd1213",
          "label":"submitButton",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "location":{
              "x":696,
              "y":510},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ef75f789e04a22b146f59889d6cb45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "location":{
                  "x":696,
                  "y":510},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Send new message<br> (If text on newMessageText does not equal &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["dc6ecc71ff64449493378fa1d5954c5b"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on messageText equal to text on newMessageText",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["779b10d138824814924a698c36fd3e0e"]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["dc6ecc71ff64449493378fa1d5954c5b"]}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show messageBubble,<br>messageText",
                      "objectsToFades":[{
                          "objectPath":["2d1f520ff6644e38ad02622a957f600d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0c0fb143b2ea4a0489ffb34713e0bbf2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFunction",
                      "description":"Set text on newMessageText equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["dc6ecc71ff64449493378fa1d5954c5b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop_chat/submitbutton_u29.png"}},
{
          "id":"1071e532f3fc44989cd2182144d242c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8396C4},
            "location":{
              "x":415,
              "y":250},
            "size":{
              "width":205,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5caeba0a9247494384cba2b3d29de862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8396C4},
                "location":{
                  "x":415,
                  "y":250},
                "size":{
                  "width":205,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u21.png"}},
{
          "id":"c2119ebeebbb447aa91c8f387fb92163",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":434,
              "y":260},
            "size":{
              "width":166,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a1c56a4efc54cb5857d98aa2b0aa20c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":260},
                "size":{
                  "width":166,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e18fe36dc24a40b8b5cc9019617d5dfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "location":{
              "x":256,
              "y":130},
            "size":{
              "width":114,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a738a814a64f93b73563de1bd7ae5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "location":{
                  "x":256,
                  "y":130},
                "size":{
                  "width":114,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u35.png"}},
{
          "id":"75bdb9d4658940b8884d78887f0cafde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":98},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f30c7a313141eda50d38cb6181497e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":98},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u37.png"}},
{
          "id":"dc6ecc71ff64449493378fa1d5954c5b",
          "label":"newMessageText",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":431,
              "y":505},
            "size":{
              "width":255,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"2d1f520ff6644e38ad02622a957f600d",
          "label":"messageBubble",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":582,
              "y":320},
            "size":{
              "width":205,
              "height":60},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f4a19f7f3004865a13a64896ebbc401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":582,
                  "y":320},
                "size":{
                  "width":205,
                  "height":60},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coffee_shop_chat/u23.png"}},
{
          "id":"0c0fb143b2ea4a0489ffb34713e0bbf2",
          "label":"messageText",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":602,
              "y":330},
            "size":{
              "width":170,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"779b10d138824814924a698c36fd3e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":602,
                  "y":330},
                "size":{
                  "width":170,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90021e5b5e884c1ab4f28409544a9ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4D69A2},
            "location":{
              "x":384,
              "y":302},
            "size":{
              "width":31,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0864ee22ca8944258b5e98c966075cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D69A2},
                "location":{
                  "x":384,
                  "y":302},
                "size":{
                  "width":31,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Coffee Shop in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"coffee_shop.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/coffee_shop_chat/u44.png"}},
{
          "id":"590f96668a5e4687b5901438e90dacaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2F4169,
              "opacity":1},
            "location":{
              "x":292,
              "y":102},
            "size":{
              "width":68,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"924ef1e11f4a419686ec27e8cd48869c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2F4169,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":102},
                "size":{
                  "width":68,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "f2fb4637bc3044a3a7de746a883444bf":{
      "packageId":"f2fb4637bc3044a3a7de746a883444bf",
      "type":"Axure:Master",
      "name":"Tablet Size",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"89ad40f4e4a845958f4f199ffc29cccd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":800,
                "height":600},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"817028217dd1407aa5e9ad17a76d4c45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":800,
                    "height":600},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}},
    "6fce1fcbd7b74a4fa90a699ee160c776":{
      "packageId":"6fce1fcbd7b74a4fa90a699ee160c776",
      "type":"Axure:Master",
      "name":"Top Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1fc2d5a32fc04aee8625a29e1baeccac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f728946738cc43f8a3e29348456955bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"888b1d943b4e4702836e8be23c5c2192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":600,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cafb9e688c2244f59a4523ca4599f297",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":600,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Event List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"event_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"98153c8ab8b44e13b4b8e2e3f725fd83",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":400,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfc399042f0b4b1f9aca768cc4b218cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":400,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Friend List in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"friend_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"15e4f70427624088850f7ffe1b5bd001",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2F4169,
                "opacity":1},
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":200,
                "height":50},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4D69A2}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2efb20853bc34548abdd42d7e54c25b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2F4169,
                    "opacity":1},
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF4D69A2}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u27.png"}}]}}},
  "objectPaths":{
    "4edc6ffe24154d4f980a050b7fb483d4":{
      "scriptId":"u0",
      "89ad40f4e4a845958f4f199ffc29cccd":{
        "scriptId":"u1"},
      "817028217dd1407aa5e9ad17a76d4c45":{
        "scriptId":"u2"}},
    "02438f8ca8b04fe0931f2c93ef53cccc":{
      "scriptId":"u3",
      "1fc2d5a32fc04aee8625a29e1baeccac":{
        "scriptId":"u4"},
      "f728946738cc43f8a3e29348456955bc":{
        "scriptId":"u5"},
      "888b1d943b4e4702836e8be23c5c2192":{
        "scriptId":"u6"},
      "cafb9e688c2244f59a4523ca4599f297":{
        "scriptId":"u7"},
      "98153c8ab8b44e13b4b8e2e3f725fd83":{
        "scriptId":"u8"},
      "cfc399042f0b4b1f9aca768cc4b218cb":{
        "scriptId":"u9"},
      "15e4f70427624088850f7ffe1b5bd001":{
        "scriptId":"u10"},
      "2efb20853bc34548abdd42d7e54c25b3":{
        "scriptId":"u11"}},
    "4aa3512d612b4fd2bc67f6f55ba6eed2":{
      "scriptId":"u12"},
    "6df6c3c2a0094db8a6fb415e983ad2b0":{
      "scriptId":"u13"},
    "7e92fa55bbf043a8896ce4afb4ce866e":{
      "scriptId":"u14"},
    "c8b1bad744394c4b9e7b9b8c0b2dc6ee":{
      "scriptId":"u15"},
    "93ae16b184ac40ce9d595350d0803427":{
      "scriptId":"u16"},
    "39068d8df3f64fafbd18b32ecbc0a7c2":{
      "scriptId":"u17"},
    "0115aa7cee6f4cc08bd44fb83133a52b":{
      "scriptId":"u18"},
    "25ae2b5ebcee47f1a15da0c93801c265":{
      "scriptId":"u19"},
    "16c8b9f240cf47a3858bc319749c78d4":{
      "scriptId":"u20"},
    "475357ba669f4a68b7bc613bc67ed94b":{
      "scriptId":"u21"},
    "978e181799314a9abe424215cbb2ba56":{
      "scriptId":"u22"},
    "cff3943629914f87a18f419a24845429":{
      "scriptId":"u23"},
    "d44de5a2e717446fb07784362eb7087a":{
      "scriptId":"u24"},
    "2db3f97c078a4e398df7ac26265c3f11":{
      "scriptId":"u25"},
    "75cf67c1a71d43ccb314d35e3db31d91":{
      "scriptId":"u26"},
    "506d29e9464f4f7ea23cda4b100b7d26":{
      "scriptId":"u27"},
    "83f8aba58c44441fab4c048ae36245c3":{
      "scriptId":"u28"},
    "cff1a13b56ce4a1c94e60fb7f9cd1213":{
      "scriptId":"u29"},
    "53ef75f789e04a22b146f59889d6cb45":{
      "scriptId":"u30"},
    "1071e532f3fc44989cd2182144d242c8":{
      "scriptId":"u31"},
    "5caeba0a9247494384cba2b3d29de862":{
      "scriptId":"u32"},
    "c2119ebeebbb447aa91c8f387fb92163":{
      "scriptId":"u33"},
    "2a1c56a4efc54cb5857d98aa2b0aa20c":{
      "scriptId":"u34"},
    "e18fe36dc24a40b8b5cc9019617d5dfe":{
      "scriptId":"u35"},
    "86a738a814a64f93b73563de1bd7ae5f":{
      "scriptId":"u36"},
    "75bdb9d4658940b8884d78887f0cafde":{
      "scriptId":"u37"},
    "52f30c7a313141eda50d38cb6181497e":{
      "scriptId":"u38"},
    "dc6ecc71ff64449493378fa1d5954c5b":{
      "scriptId":"u39"},
    "2d1f520ff6644e38ad02622a957f600d":{
      "scriptId":"u40"},
    "9f4a19f7f3004865a13a64896ebbc401":{
      "scriptId":"u41"},
    "0c0fb143b2ea4a0489ffb34713e0bbf2":{
      "scriptId":"u42"},
    "779b10d138824814924a698c36fd3e0e":{
      "scriptId":"u43"},
    "90021e5b5e884c1ab4f28409544a9ec6":{
      "scriptId":"u44"},
    "0864ee22ca8944258b5e98c966075cda":{
      "scriptId":"u45"},
    "590f96668a5e4687b5901438e90dacaf":{
      "scriptId":"u46"},
    "924ef1e11f4a419686ec27e8cd48869c":{
      "scriptId":"u47"}}});